### ISSUE TITLE
Ime repozitorija

### ISSUE THREAD

**Issue by jaanos** [TomasRode/ProjektSage#1]
@TomasRode, svetujem, da ima repozitorij bolj pomenljivo ime, npr. `Nanotori`. Ime spremeniš tako, da zgoraj klikneš na *Settings*, nato pa spremeniš ime pod **Repository name**.

Mimogrede, mapa `.ipynb_checkpoints` ne sodi na repozitorij, saj gre za avtomatsko shranjena vmesna stanja. Svetujem, da mapo pobrišeta in poskrbita še za ustrezno datoteko `.gitignore`, ki bo preprečila ponovno dodajanje mape. Ne pozabita seveda tudi dodati povezave do repozitorija na wiki na spletni učilnici.

**Comment by TomasRode** [comment]
Hvala za nasvet. Mislim, da sem popravil.  Imava pa neko težavo z določanjem točk, ki sodijo v paralelogram. Sem odprl nov issue.

**Comment by jaanos** [comment]
V redu, bom zaprl issue - seveda ga pa lahko tudi sama zapreta, ko razrešita zadevo.
